//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkazStran
{
    using System;
    using System.Collections.Generic;

    public partial class Master
    {
        public string FIO { get; set; }
        public int tubNUM { get; set; }
        public Nullable<System.DateTime> dateStartWork { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string State { get; set; }
    }
}
