//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkazStran
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToyInOrder
    {
        public int idToy { get; set; }
        public int idOrder { get; set; }
        public int count { get; set; }
        public string nazv { get { return Toy.title; } }
        public decimal cost { get { return Toy.costForOne * count; } }
        public DateTime date { get { return Order.date; } }
        public int stat { get { return Order.state; } }

        public virtual Order Order { get; set; }
        public virtual Toy Toy { get; set; }
    }
}
